# Generated by Django 4.1.6 on 2023-02-23 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('prod_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('prod_select', models.BooleanField()),
                ('prod_name', models.CharField(choices=[('sc', 'stream chemistry'), ('sd', 'stream discharge'), ('pc', 'precipitation chemistry'), ('pv', 'precipitation volume')], max_length=50)),
            ],
        ),
    ]
