# Generated by Django 4.1.6 on 2023-02-24 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_name',
            field=models.CharField(choices=[('stream chemistry', 'stream chemistry'), ('sstream discharge', 'stream discharge'), ('precipitation chemistry', 'precipitation chemistry'), ('precipitation volume', 'precipitation volume')], max_length=50),
        ),
    ]
